
%% CEC_VERSION_UNKNOWN = 0x00,
%% CEC_VERSION_1_2     = 0x01,
%% CEC_VERSION_1_2A    = 0x02,
%% CEC_VERSION_1_3     = 0x03,
%% CEC_VERSION_1_3A    = 0x04,
%% CEC_VERSION_1_4     = 0x05


%% logical address to devices
-define(LADDR_TV, 0).
-define(LADDR_RECDEV1, 1).
-define(LADDR_RECDEV2, 2).
-define(LADDR_TUNER1, 3).
-define(LADDR_PLAYBDEV1, 4).
-define(LADDR_AUDIOSYS, 5).
-define(LADDR_TUNER2, 6).
-define(LADDR_TUNER3, 7).
-define(LADDR_PLAYBDEV2, 8).
-define(LADDR_RECDEV3, 9).
-define(LADDR_TUNER4, 10).
-define(LADDR_PLAYBDEV3, 11).
-define(LADDR_RESERVED1, 12).
-define(LADDR_RESERVED2, 13).
-define(LADDR_FREEUSE, 14).
-define(LADDR_UNREG, 15).
-define(LADDR_BROADCAST, 15).


-define(CEC_ACTIVE_SOURCE, 16#82).
-define(CEC_IMAGE_VIEW_ON, 16#04).
-define(CEC_TEXT_VIEW_ON, 16#0D).
-define(CEC_INACTIVE_SOURCE, 16#9D).
-define(CEC_REQUEST_ACTIVE_SOURCE, 16#85).
-define(CEC_ROUTING_CHANGE, 128). %16#80
-define(CEC_ROUTING_INFORMATION, 16#81).
-define(CEC_SET_STREAM_PATH, 134). %16#86
-define(CEC_STANDBY, 16#36).
-define(CEC_RECORD_OFF, 16#0B).
-define(CEC_RECORD_ON, 16#09).
-define(CEC_RECORD_STATUS, 16#0A).
-define(CEC_RECORD_TV_SCREEN, 16#0F).
-define(CEC_CLEAR_ANALOGUE_TIMER, 16#33).
-define(CEC_CLEAR_DIGITAL_TIMER, 16#99).
-define(CEC_CLEAR_EXTERNAL_TIMER, 16#A1).
-define(CEC_SET_ANALOGUE_TIMER, 16#34).
-define(CEC_SET_DIGITAL_TIMER, 16#97).
-define(CEC_SET_EXTERNAL_TIMER, 16#A2).
-define(CEC_SET_TIMER_PROGRAM_TITLE, 16#67).
-define(CEC_TIMER_CLEARED_STATUS, 16#43).
-define(CEC_TIMER_STATUS, 16#35).
-define(CEC_CEC_VERSION, 16#9E).
-define(CEC_GET_CEC_VERSION, 16#9F).
-define(CEC_GIVE_PHYSICAL_ADDRESS, 16#83).
-define(CEC_GET_MENU_LANGUAGE, 16#91).
-define(CEC_REPORT_PHYSICAL_ADDRESS, 16#84).
-define(CEC_SET_MENU_LANGUAGE, 16#32).
-define(CEC_DECK_CONTROL, 16#42).
-define(CEC_DECK_STATUS, 16#1B).
-define(CEC_GIVE_DECK_STATUS, 16#1A).
-define(CEC_PLAY, 16#41).
-define(CEC_GIVE_TUNER_DEVICE_STATUS, 16#08).
-define(CEC_SELECT_ANALOGUE_SERVICE, 16#92).
-define(CEC_SELECT_DIGITAL_SERVICE, 16#93).
-define(CEC_TUNER_DEVICE_STATUS, 16#07).
-define(CEC_TUNER_STEP_DECREMENT, 16#06).
-define(CEC_TUNER_STEP_INCREMENT, 16#05).
-define(CEC_DEVICE_VENDOR_ID, 16#87).
-define(CEC_GIVE_DEVICE_VENDOR_ID, 16#8C).
-define(CEC_VENDOR_COMMAND, 16#89).
-define(CEC_VENDOR_COMMAND_WITH_ID, 16#A0).
-define(CEC_VENDOR_REMOTE_BUTTON_DOWN, 16#8A).
-define(CEC_VENDOR_REMOTE_BUTTON_UP, 16#8B).
-define(CEC_SET_OSD_STRING, 16#64).
-define(CEC_GIVE_OSD_NAME, 16#46).
-define(CEC_SET_OSD_NAME, 16#47).
-define(CEC_MENU_REQUEST, 16#8D).
-define(CEC_MENU_STATUS, 142). %16#8E
-define(CEC_USER_CONTROL_PRESSED, 68). %16#44
-define(CEC_USER_CONTROL_RELEASE, 69). %16#45
-define(CEC_GIVE_DEVICE_POWER_STATUS, 16#8F).
-define(CEC_REPORT_POWER_STATUS, 16#90).
-define(CEC_FEATURE_ABORT, 16#00).
-define(CEC_ABORT, 16#FF).
-define(CEC_GIVE_AUDIO_STATUS, 113). %16#71
-define(CEC_GIVE_SYSTEM_AUDIO_MODE_STATUS, 16#7D).
-define(CEC_REPORT_AUDIO_STATUS, 16#7A).
-define(CEC_SYSTEM_AUDIO_MODE_REQUEST, 112). %16#70
-define(CEC_SET_SYSTEM_AUDIO_MODE, 114). %16#72
-define(CEC_SYSTEM_AUDIO_MODE_STATUS, 16#7E).
-define(CEC_SET_AUDIO_RATE, 16#9A).

%% CEC 1.4
-define(CEC_START_ARC, 190). %16#C0
-define(CEC_REPORT_ARC_STARTED, 193). %16#C1
-define(CEC_REPORT_ARC_ENDED, 16#C2).
-define(CEC_REQUEST_ARC_START, 195). %16#C3
-define(CEC_REQUEST_ARC_END, 16#C4).
-define(CEC_END_ARC, 197). %16#C5
-define(CEC_CDC, 16#F8).

%% when this opcode is set, no opcode will be sent to the device. this
%% is one of the reserved numbers
-define(CEC_NONE, 16#FD).
